### ISSUE TITLE
Python 3.6 on debian stretch

### ISSUE THREAD

**Issue by robpottify** [demartis/matlab_runtime_docker#5]
Hey. 
Great work on the image - nice to see the silent MCR install working. I'm playing with this image trying to call MCR from python - I've compiled a python interop using the MATLAB Compiler. I've got this fully working on an Ubuntu 18.04 image, but I'd love to leverage your image as a base. Problem is that debian stretch only supports up to python 3.5, but MCR requires 3.6/3.7. I'd rather not hack python 3.6 onto stretch; prefer to use the better supported apt-get route.

So I am planning to build out my own image on debian buster. Is there any reason you've stayed on stretch and not upgraded this project?

**Comment by demartis** [comment]
Hey @robpottify, the project has just been updated. Thank you for commenting
