### ISSUE TITLE
Matlab runtime 2021a (v.9.10)

### ISSUE THREAD

**Issue by Laura-Bueno** [demartis/matlab_runtime_docker#6]
Hi @demartis 

I need to install matlab runtime 2021a in a linux vm for my application to be able to run. Just wondering if you also have a repository for that version please?

Thanks so much in advance!

**Comment by Laura-Bueno** [comment]
Hi @demartis,

I have been able to compile my application using matlab 2019b so I have been able to pull the image from your repository by using "docker pull demartis/matlab-runtime:2019b". Next, I import the image to my dockerfile and built the image for my application. However, when I try to run the container I get the following error:

RuntimeError: Could not find an appropriate directory for MATLAB or the MATLAB runtime in LD_LIBRARY_PATH. Details: libmwmclmcrrt.so.9.7

I've seen that in your dockerfile, the library path is set up to the following path however when I check this path in the vm doesn't exist for me. Any ideas what could be happening?

ENV LD_LIBRARY_PATH /opt/mcr/v97/runtime/glnxa64:/opt/mcr/v97/bin/glnxa64:/opt/mcr/v97/sys/os/glnxa64:/opt/mcr/v97/extern/bin/glnxa64

thanks a lot in advance

**Comment by qbmiller** [comment]
eg: use centos docker image.     I install MATLAB_Runtime_R2020a_Update_7_glnxa64 yestoday, it works well. 
python3 version:3.6.9

**Comment by DuGengXin** [comment]
> 

I need it too, bro, but I need 2021b,I've been trying to make my own

**Comment by demartis** [comment]
hello, @qbmiller  and @Laura-Bueno , I've been working on new releases, newest MATLAB versions will be available soon

**Comment by demartis** [comment]
Project up to date
