### ISSUE TITLE
runtime with others licensed toolboxes

### ISSUE THREAD

**Issue by makovez** [demartis/matlab_runtime_docker#8]
Is it possible to modify the runtime to add other toolboxes for which I'm licensed to?

I'm unable to run my matlab executable with your dockerfile because it uses some toolboxes which don't seem available the one listed in this runtime readme

**Comment by demartis** [comment]
Hi @makovez, I am updating the project and taking over this issue now, I couldn't manage it before. Which toolboxes would you need? What Matlab version?

**Comment by makovez** [comment]
Hi I can't remember the toolboxes but I solved already the issue by using their official runtime docker version containers.mathworks.com/matlab-runtime:r2023a

Also I don't think you can modify which toolboxes you want install as what you download from https://ssd.mathworks.com/supportfiles/downloads/R2023a/Release/2/deployment_files/installer/complete/glnxa64/MATLAB_Runtime_R2023a_Update_2_glnxa64.zip should already include all toolboxes

Also from what I remember, I think the problem was not related with the toolboxes in reality

**Comment by demartis** [comment]
Indeed, as far as I knew  the Runtime installers contain all toolboxes. Thanks for contribuiting with this  :)
